-- Migration 004: seed full currency list
-- Uses INSERT OR IGNORE to preserve any existing rows (EUR was seeded in 002).
-- minor_units per ISO 4217 and standard alternative-asset conventions.
BEGIN TRANSACTION;

INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('AED', 'UAE Dirham', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('AFN', 'Afghan Afghani', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ALL', 'Albanian Lek', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('AMD', 'Armenian Dram', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ANG', 'Netherlands Antillean Guilder', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('AOA', 'Angolan Kwanza', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ARS', 'Argentine Peso', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('AUD', 'Australian Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('AWG', 'Aruban Florin', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('AZN', 'Azerbaijani Manat', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BAM', 'Bosnia-Herzegovina Convertible Mark', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BBD', 'Barbadian Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BDT', 'Bangladeshi Taka', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BGN', 'Bulgarian Lev', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BHD', 'Bahraini Dinar', 3);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BIF', 'Burundian Franc', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BMD', 'Bermudan Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BND', 'Brunei Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BOB', 'Bolivian Boliviano', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BRL', 'Brazilian Real', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BSD', 'Bahamian Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BTC', 'Bitcoin', 8);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BTN', 'Bhutanese Ngultrum', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BWP', 'Botswanan Pula', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BYN', 'Belarusian Ruble', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BYR', 'Belarusian Ruble (old)', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('BZD', 'Belize Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CAD', 'Canadian Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CDF', 'Congolese Franc', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CHF', 'Swiss Franc', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CLF', 'Chilean Unit of Account (UF)', 4);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CLP', 'Chilean Peso', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CNH', 'Chinese Yuan (Offshore)', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CNY', 'Chinese Yuan', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('COP', 'Colombian Peso', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CRC', 'Costa Rican Colon', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CUC', 'Cuban Convertible Peso', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CUP', 'Cuban Peso', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CVE', 'Cape Verdean Escudo', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('CZK', 'Czech Koruna', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('DJF', 'Djiboutian Franc', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('DKK', 'Danish Krone', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('DOP', 'Dominican Peso', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('DZD', 'Algerian Dinar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('EGP', 'Egyptian Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ERN', 'Eritrean Nakfa', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ETB', 'Ethiopian Birr', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ETH', 'Ethereum', 8);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('EUR', 'Euro', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('FJD', 'Fijian Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('FKP', 'Falkland Islands Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GBP', 'British Pound Sterling', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GEL', 'Georgian Lari', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GGP', 'Guernsey Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GHS', 'Ghanaian Cedi', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GIP', 'Gibraltar Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GMD', 'Gambian Dalasi', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GNF', 'Guinean Franc', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GTQ', 'Guatemalan Quetzal', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('GYD', 'Guyanaese Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('HKD', 'Hong Kong Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('HNL', 'Honduran Lempira', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('HRK', 'Croatian Kuna', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('HTG', 'Haitian Gourde', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('HUF', 'Hungarian Forint', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('IDR', 'Indonesian Rupiah', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ILS', 'Israeli New Shekel', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('IMP', 'Manx Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('INR', 'Indian Rupee', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('IQD', 'Iraqi Dinar', 3);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('IRR', 'Iranian Rial', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ISK', 'Icelandic Krona', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('JEP', 'Jersey Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('JMD', 'Jamaican Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('JOD', 'Jordanian Dinar', 3);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('JPY', 'Japanese Yen', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KES', 'Kenyan Shilling', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KGS', 'Kyrgystani Som', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KHR', 'Cambodian Riel', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KMF', 'Comorian Franc', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KPW', 'North Korean Won', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KRW', 'South Korean Won', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KWD', 'Kuwaiti Dinar', 3);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KYD', 'Caymanian Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('KZT', 'Kazakhstani Tenge', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('LAK', 'Laotian Kip', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('LBP', 'Lebanese Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('LKR', 'Sri Lankan Rupee', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('LRD', 'Liberian Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('LSL', 'Lesotho Loti', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('LYD', 'Libyan Dinar', 3);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MAD', 'Moroccan Dirham', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MDL', 'Moldovan Leu', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MGA', 'Malagasy Ariary', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MKD', 'Macedonian Denar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MMK', 'Myanma Kyat', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MNT', 'Mongolian Togrog', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MOP', 'Macanese Pataca', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MRO', 'Mauritanian Ouguiya (old)', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MRU', 'Mauritanian Ouguiya', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MUR', 'Mauritian Rupee', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MVR', 'Maldivian Rufiyaa', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MWK', 'Malawian Kwacha', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MXN', 'Mexican Peso', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MYR', 'Malaysian Ringgit', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('MZN', 'Mozambican Metical', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('NAD', 'Namibian Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('NGN', 'Nigerian Naira', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('NIO', 'Nicaraguan Cordoba', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('NOK', 'Norwegian Krone', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('NPR', 'Nepalese Rupee', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('NZD', 'New Zealand Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('OMR', 'Omani Rial', 3);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('PAB', 'Panamanian Balboa', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('PEN', 'Peruvian Sol', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('PGK', 'Papua New Guinean Kina', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('PHP', 'Philippine Peso', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('PKR', 'Pakistani Rupee', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('PLN', 'Polish Zloty', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('PYG', 'Paraguayan Guarani', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('QAR', 'Qatari Rial', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('RON', 'Romanian Leu', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('RSD', 'Serbian Dinar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('RUB', 'Russian Ruble', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('RWF', 'Rwandan Franc', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SAR', 'Saudi Riyal', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SBD', 'Solomon Islands Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SCR', 'Seychellois Rupee', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SDG', 'Sudanese Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SEK', 'Swedish Krona', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SGD', 'Singapore Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SHP', 'Saint Helena Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SLE', 'Sierra Leonean Leone', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SLL', 'Sierra Leonean Leone', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SOS', 'Somali Shilling', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SRD', 'Surinamese Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SSP', 'South Sudanese Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('STD', 'Sao Tome and Principe Dobra (old)', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('STN', 'Sao Tome and Principe Dobra', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SVC', 'Salvadoran Colon', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SYP', 'Syrian Pound', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('SZL', 'Swazi Lilangeni', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('THB', 'Thai Baht', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('TJS', 'Tajikistani Somoni', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('TMT', 'Turkmenistani Manat', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('TND', 'Tunisian Dinar', 3);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('TOP', 'Tongan Paanga', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('TRY', 'Turkish Lira', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('TTD', 'Trinidad and Tobago Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('TWD', 'New Taiwan Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('TZS', 'Tanzanian Shilling', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('UAH', 'Ukrainian Hryvnia', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('UGX', 'Ugandan Shilling', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('USD', 'United States Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('UYU', 'Uruguayan Peso', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('UZS', 'Uzbekistan Som', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('VEF', 'Venezuelan Bolivar Fuerte (old)', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('VES', 'Venezuelan Bolivar Soberano', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('VND', 'Vietnamese Dong', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('VUV', 'Vanuatu Vatu', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('WST', 'Samoan Tala', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XAF', 'CFA Franc BEAC', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XAG', 'Silver (troy ounce)', 4);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XAU', 'Gold (troy ounce)', 4);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XCD', 'East Caribbean Dollar', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XCG', 'Caribbean Guilder', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XDR', 'Special Drawing Rights', 5);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XOF', 'CFA Franc BCCI', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XPD', 'Palladium Ounce', 4);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XPF', 'CFP Franc', 0);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('XPT', 'Platinum Ounce', 4);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('YER', 'Yemeni Rial', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ZAR', 'South African Rand', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ZMW', 'Zambian Kwacha', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ZWG', 'Zimbabwean ZiG', 2);
INSERT OR IGNORE INTO currency (code, name, minor_units) VALUES ('ZWL', 'Zimbabwean Dollar', 2);

COMMIT;
